// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtuojVQXYGAfXEvjFZiG9ZL7vK98aPXXk',
    appId: '1:676308462405:web:a5f75a4a564f86480dec2c',
    messagingSenderId: '676308462405',
    projectId: 'onsite-c044c',
    authDomain: 'onsite-c044c.firebaseapp.com',
    storageBucket: 'onsite-c044c.appspot.com',
    measurementId: 'G-PX4NP8W835',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlNVtDZjOuxL16IJibFwkezmTHAsrEdsU',
    appId: '1:676308462405:android:d2e500e779463d1c0dec2c',
    messagingSenderId: '676308462405',
    projectId: 'onsite-c044c',
    storageBucket: 'onsite-c044c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9aJuapSlvSjCinmkbQayU46YfbKaPukg',
    appId: '1:676308462405:ios:6e25dfe143e544170dec2c',
    messagingSenderId: '676308462405',
    projectId: 'onsite-c044c',
    storageBucket: 'onsite-c044c.appspot.com',
    iosBundleId: 'com.example.onsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9aJuapSlvSjCinmkbQayU46YfbKaPukg',
    appId: '1:676308462405:ios:6e25dfe143e544170dec2c',
    messagingSenderId: '676308462405',
    projectId: 'onsite-c044c',
    storageBucket: 'onsite-c044c.appspot.com',
    iosBundleId: 'com.example.onsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtuojVQXYGAfXEvjFZiG9ZL7vK98aPXXk',
    appId: '1:676308462405:web:2dc10e89734786e30dec2c',
    messagingSenderId: '676308462405',
    projectId: 'onsite-c044c',
    authDomain: 'onsite-c044c.firebaseapp.com',
    storageBucket: 'onsite-c044c.appspot.com',
    measurementId: 'G-YHBR9Z6YHD',
  );
}
